//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDeliverySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_list()
        {
            this.order_tbl = new HashSet<order_tbl>();
        }
    
        public int id { get; set; }
        public int order_id { get; set; }
        public int item { get; set; }
        public string quantity { get; set; }
        public decimal price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_tbl> order_tbl { get; set; }
    }
}
