//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDeliverySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_tbl
    {
        public int id { get; set; }
        public int order_list_id { get; set; }
        public int user_id { get; set; }
        public int restaurant_id { get; set; }
        public byte[] date { get; set; }
    
        public virtual order_list order_list { get; set; }
        public virtual restaurant_tbl restaurant_tbl { get; set; }
        public virtual user_tbl user_tbl { get; set; }
    }
}
