//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDeliverySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurant_delivery_systemEntities1 : DbContext
    {
        public restaurant_delivery_systemEntities1()
            : base("name=restaurant_delivery_systemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<menu_tbl> menu_tbl { get; set; }
        public virtual DbSet<order_list> order_list { get; set; }
        public virtual DbSet<order_tbl> order_tbl { get; set; }
        public virtual DbSet<restaurant_tbl> restaurant_tbl { get; set; }
        public virtual DbSet<user_tbl> user_tbl { get; set; }
    }
}
